// CymruBlazor.CssBundler
//
// Bundles CymruBlazor's dev-mode CSS entry point into a single stylesheet
// with no runtime @import statements, for use in Release/Publish builds
// and the packed NuGet package.
//
// The entry point file (wwwroot/css/cymrublazor.css) already lists every
// stylesheet and the cascade layer it belongs to, as statements shaped
// like:
//
//     @import "tokens/colours.css" layer(tokens);
//
// This tool parses those statements directly, rather than maintaining a
// second, separately-ordered list elsewhere - two lists describing the
// same thing are the classic way this kind of build step quietly drifts
// out of sync. The entry point is the only file anyone needs to edit when
// a stylesheet is added, removed or reordered.
//
// Usage:
//   CymruBlazor.CssBundler <entrypoint-css-path> <output-css-path>

using System.Text;
using System.Text.RegularExpressions;

if (args.Length != 2)
{
    Console.Error.WriteLine(
        "Usage: CymruBlazor.CssBundler <entrypoint-css-path> <output-css-path>");
    return 1;
}

var entryPointPath = Path.GetFullPath(args[0]);
var outputPath = Path.GetFullPath(args[1]);

if (!File.Exists(entryPointPath))
{
    Console.Error.WriteLine(
        $"CymruBlazor.CssBundler: entry point not found: '{entryPointPath}'.");
    return 1;
}

var entryPointDirectory = Path.GetDirectoryName(entryPointPath);
if (string.IsNullOrEmpty(entryPointDirectory))
{
    Console.Error.WriteLine(
        $"CymruBlazor.CssBundler: could not determine the directory of '{entryPointPath}'.");
    return 1;
}

var entryPointText = File.ReadAllText(entryPointPath);

// The layer precedence order, declared once near the top of the entry
// point, e.g.:
//   @layer reset, tokens, base, layout, components, utilities, overrides;
var layerOrderMatch = Regex.Match(entryPointText, @"@layer\s+[a-zA-Z0-9_,\s-]+;");

if (!layerOrderMatch.Success)
{
    Console.Error.WriteLine(
        "CymruBlazor.CssBundler: could not find a '@layer a, b, c;' " +
        $"precedence declaration in '{entryPointPath}'.");
    return 1;
}

// Each imported stylesheet and the layer it belongs to, e.g.:
//   @import "base/reset.css" layer(reset);
var importPattern = new Regex(
    @"@import\s+""(?<path>[^""]+)""\s+layer\((?<layer>[^)]+)\)\s*;");

var importMatches = importPattern.Matches(entryPointText);

if (importMatches.Count == 0)
{
    Console.Error.WriteLine(
        "CymruBlazor.CssBundler: no '@import \"path\" layer(name);' " +
        $"statements found in '{entryPointPath}'.");
    return 1;
}

var output = new StringBuilder();

output.AppendLine("/*");
output.AppendLine(" * CymruBlazor - bundled stylesheet.");
output.AppendLine(" *");
output.AppendLine(" * Generated by tools/CymruBlazor.CssBundler from:");
output.AppendLine($" *   {Path.GetFileName(entryPointPath)}");
output.AppendLine(" *");
output.AppendLine(" * Do not edit this file directly. Edit the individual");
output.AppendLine(" * stylesheets, and the @import list above, instead.");
output.AppendLine(" */");
output.AppendLine();
output.AppendLine(layerOrderMatch.Value);

var bundledCount = 0;

foreach (Match match in importMatches)
{
    var relativePath = match.Groups["path"].Value;
    var layerName = match.Groups["layer"].Value.Trim();

    var sourcePath = Path.GetFullPath(Path.Combine(entryPointDirectory, relativePath));

    if (!File.Exists(sourcePath))
    {
        Console.Error.WriteLine(
            $"CymruBlazor.CssBundler: '{relativePath}' (referenced from " +
            $"'{Path.GetFileName(entryPointPath)}') was not found at '{sourcePath}'.");
        return 1;
    }

    var css = File.ReadAllText(sourcePath).Trim();

    output.AppendLine();
    output.AppendLine($"/* ---- {relativePath} ---- */");
    output.AppendLine($"@layer {layerName} {{");
    output.AppendLine(css);
    output.AppendLine("}");

    bundledCount++;
}

var outputDirectory = Path.GetDirectoryName(outputPath);
if (string.IsNullOrEmpty(outputDirectory))
{
    Console.Error.WriteLine(
        $"CymruBlazor.CssBundler: could not determine the directory of '{outputPath}'.");
    return 1;
}

Directory.CreateDirectory(outputDirectory);

// No BOM: this file is served as-is over HTTP as a static web asset.
File.WriteAllText(outputPath, output.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

Console.WriteLine(
    $"CymruBlazor.CssBundler: bundled {bundledCount} stylesheet(s) into '{outputPath}'.");

return 0;
