<#
.SYNOPSIS
  Packs CymruBlazor into ./artifacts and points the samples' central
  package version at whatever version MinVer actually produced.

.DESCRIPTION
  MinVer computes a new package version on every commit (the height above
  the nearest Git tag is baked into the prerelease identifier - see
  CONTRIBUTING.md). That means there is no fixed version string that can
  correctly be hand-typed into Directory.Packages.props for local
  development: it goes stale the moment another commit is made.

  This script packs the library, reads the *actual* version off the
  resulting .nupkg filename (NuGet's own packing convention is always
  "{PackageId}.{Version}.nupkg", and "CymruBlazor" contains no dots, so
  this is unambiguous), and writes that version into
  local-package-versions.props at the repo root. Directory.Packages.props
  imports that file (if present) and overrides the CymruBlazor
  PackageVersion with it, so samples/StarterApp, samples/Dashboard and
  samples/HealthcarePortal always restore against whatever was just
  packed - not a number someone typed by hand last week.

  local-package-versions.props is git-ignored: it is a local build
  artefact, not a source-controlled version pin.

.EXAMPLE
  ./New-LocalPackageFeed.ps1
#>

param(
  [string]$RootPath = ".",
  [string]$ArtifactsDir = "artifacts"
)

$ErrorActionPreference = "Stop"

$Root = (Resolve-Path -Path $RootPath).ProviderPath
Push-Location $Root

try {
  $artifactsPath = Join-Path $Root $ArtifactsDir

  # artifacts/.gitkeep keeps this directory present on a fresh clone (a
  # missing local NuGet source fails restore repo-wide with NU1301, not
  # just for the samples) - this is just defensive in case it's been
  # deleted locally.
  New-Item -ItemType Directory -Force -Path $artifactsPath | Out-Null

  Write-Host "Packing src/CymruBlazor/CymruBlazor.csproj -> $artifactsPath ..." -ForegroundColor Cyan

  dotnet pack `
    (Join-Path $Root "src/CymruBlazor/CymruBlazor.csproj") `
    -c Release `
    -o $artifactsPath

  if ($LASTEXITCODE -ne 0) {
    throw "dotnet pack failed with exit code $LASTEXITCODE."
  }

  # NuGet's packing convention is always "{PackageId}.{Version}.nupkg" -
  # exclude the .snupkg symbol package, which shares the same prefix.
  $nupkg = Get-ChildItem -Path $artifactsPath -Filter "CymruBlazor.*.nupkg" -File |
    Where-Object { $_.Name -notlike "*.snupkg" } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

  if ($null -eq $nupkg) {
    throw "No CymruBlazor.*.nupkg found in $artifactsPath after packing."
  }

  if ($nupkg.Name -notmatch '^CymruBlazor\.(?<version>.+)\.nupkg$') {
    throw "Could not parse a version out of package filename '$($nupkg.Name)'."
  }

  $version = $Matches['version']

  Write-Host "Packed version: $version" -ForegroundColor Green

  $propsPath = Join-Path $Root "local-package-versions.props"

  $propsContent = @"
<Project>
  <!--
    Generated by New-LocalPackageFeed.ps1 - do not edit by hand, and do
    not commit this file (see .gitignore). Re-run the script after every
    commit that should be reflected in the samples' local package feed.
  -->
  <ItemGroup>
    <PackageVersion Update="CymruBlazor" Version="$version" />
  </ItemGroup>
</Project>
"@

  Set-Content -Path $propsPath -Value $propsContent -Encoding utf8

  Write-Host "Wrote $propsPath" -ForegroundColor Green
  Write-Host ""
  Write-Host "The samples will now restore CymruBlazor $version from ./$ArtifactsDir."
  Write-Host "Re-run this script whenever you want the samples to pick up local changes."
}
finally {
  Pop-Location
}
