#:property PublishAot=false
// Generates the design-token artefacts from the library's own CSS, and checks
// the rules that keep theming correct.
//
//   dotnet run scripts/GenerateTokens.cs            # regenerate files
//   dotnet run scripts/GenerateTokens.cs -- --check # CI: fail if stale or a rule is broken
//
// Single source of truth: src/CymruBlazor/wwwroot/css/{tokens,themes}/*.css.
// Outputs (never hand-edit):
//   src/CymruBlazor/wwwroot/css/tokens/colour-aliases.generated.css  UK-spelling --cymru-colour-* aliases
//   src/CymruBlazor/wwwroot/tokens/tokens.json                       machine-readable token list
//   src/CymruBlazor/wwwroot/tokens/tokens.d.ts                       union type of every token name
//   docs/design-tokens.md                                            human-readable reference
//
// --check also enforces the THEME-SCOPING RULE (see tokens/aliases.css): a token
// whose value derives (via var()) from a token that a theme overrides must itself
// be declared in a theme scope, or be overridden by that theme. Otherwise it is
// resolved once on :root and the theme's override never reaches it.

using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

var check = args.Contains("--check");
static void L(StringBuilder b, string line) => b.Append(line).Append('\n');
var root = FindRoot();
var cssRoot = Path.Combine(root, "src", "CymruBlazor", "wwwroot", "css");

var comment = new Regex(@"/\*.*?\*/", RegexOptions.Singleline | RegexOptions.Compiled);
var rule = new Regex(@"([^{}]+)\{([^{}]*)\}", RegexOptions.Compiled);
var decl = new Regex(@"(--[A-Za-z0-9_-]+)\s*:\s*([^;]+);", RegexOptions.Compiled);
var varRef = new Regex(@"var\(\s*(--[A-Za-z0-9_-]+)", RegexOptions.Compiled);

// (file, selector, name, value)
var decls = new List<(string File, string Selector, string Name, string Value)>();
foreach (var dir in new[] { "tokens", "themes" })
{
    foreach (var file in Directory.EnumerateFiles(Path.Combine(cssRoot, dir), "*.css").OrderBy(f => f, StringComparer.Ordinal))
    {
        if (file.EndsWith(".generated.css", StringComparison.Ordinal)) continue;
        var css = comment.Replace(File.ReadAllText(file), "");
        var rel = $"{dir}/{Path.GetFileName(file)}";
        foreach (Match r in rule.Matches(css))
        {
            var selector = Regex.Replace(r.Groups[1].Value.Trim(), @"\s+", " ");
            foreach (Match d in decl.Matches(r.Groups[2].Value))
                decls.Add((rel, selector, d.Groups[1].Value, Regex.Replace(d.Groups[2].Value.Trim(), @"\s+", " ")));
        }
    }
}

bool IsTheme(string file, string name) => file == $"themes/{name}.css";
bool ThemeScoped(string selector) => selector.Contains("[data-theme", StringComparison.Ordinal) && !selector.Contains(":root", StringComparison.Ordinal)
    || selector.Contains("body:has(", StringComparison.Ordinal);

// Base value: first declaration in tokens/*.css (the shipped defaults).
var baseDecl = decls.Where(d => d.File.StartsWith("tokens/", StringComparison.Ordinal))
    .GroupBy(d => d.Name).ToDictionary(g => g.Key, g => g.First());
var dark = decls.Where(d => IsTheme(d.File, "dark")).GroupBy(d => d.Name).ToDictionary(g => g.Key, g => g.Last().Value);
var hc = decls.Where(d => IsTheme(d.File, "high-contrast")).GroupBy(d => d.Name).ToDictionary(g => g.Key, g => g.Last().Value);
var allNames = decls.Select(d => d.Name).Where(n => n.StartsWith("--cymru-", StringComparison.Ordinal)).Distinct().OrderBy(n => n, StringComparer.Ordinal).ToList();

string Category(string name)
{
    if (!baseDecl.TryGetValue(name, out var b)) return "theme-only";
    return Path.GetFileNameWithoutExtension(b.File) switch
    {
        "colours" => name.StartsWith("--cymru-color-", StringComparison.Ordinal) ? "colour (semantic)" : "colour (primitive)",
        "aliases" => "alias",
        var other => other,
    };
}

// ---------- generated outputs ----------
var outputs = new Dictionary<string, string>();

// 1. UK-spelling aliases
var colourNames = allNames.Where(n => n.StartsWith("--cymru-color-", StringComparison.Ordinal)).ToList();
var sb = new StringBuilder();
L(sb, "/*");
L(sb, " * GENERATED by scripts/GenerateTokens.cs - do not edit.");
L(sb, " *");
L(sb, " * UK-spelling aliases (--cymru-colour-*) for every --cymru-color-* token.");
L(sb, " * Declared on every theme scope for the same reason as tokens/aliases.css:");
L(sb, " * each alias must re-resolve inside a theme provider.");
L(sb, " */");
L(sb, "");
L(sb, ":root,");
L(sb, "[data-theme],");
L(sb, "body:has(.cy-theme-provider[data-theme]) {");
foreach (var n in colourNames)
    L(sb, $"  --cymru-colour-{n["--cymru-color-".Length..]}: var({n});");
L(sb, "}");
outputs[Path.Combine(cssRoot, "tokens", "colour-aliases.generated.css")] = sb.ToString();

// 2. tokens.json
var json = allNames.Select(n => new SortedDictionary<string, string?>(StringComparer.Ordinal)
{
    ["name"] = n,
    ["category"] = Category(n),
    ["value"] = baseDecl.TryGetValue(n, out var bd) ? bd.Value : null,
    ["dark"] = dark.GetValueOrDefault(n),
    ["highContrast"] = hc.GetValueOrDefault(n),
}.Where(kv => kv.Value is not null).ToDictionary(kv => kv.Key, kv => kv.Value!)).ToList();
#pragma warning disable CA1869 // single use in a one-shot tool
var jsonOpts = new JsonSerializerOptions { WriteIndented = true, Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
outputs[Path.Combine(root, "src", "CymruBlazor", "wwwroot", "tokens", "tokens.json")] =
    JsonSerializer.Serialize(new { tokens = json }, jsonOpts) + "\n";
#pragma warning restore CA1869

// 3. tokens.d.ts
var dts = new StringBuilder();
L(dts, "// GENERATED by scripts/GenerateTokens.cs - do not edit.");
L(dts, "// Every CymruBlazor design token name, for typed lookups and lint rules.");
L(dts, "export type CymruTokenName =");
for (var i = 0; i < allNames.Count; i++)
    L(dts, $"  | \"{allNames[i]}\"{(i == allNames.Count - 1 ? ";" : "")}");
outputs[Path.Combine(root, "src", "CymruBlazor", "wwwroot", "tokens", "tokens.d.ts")] = dts.ToString();

// 4. docs/design-tokens.md
var md = new StringBuilder();
L(md, "# CymruBlazor design tokens");
L(md, "");
L(md, "> **Generated** by `scripts/GenerateTokens.cs` from `wwwroot/css/{tokens,themes}`. Do not edit by hand;");
L(md, "> run `dotnet run scripts/GenerateTokens.cs` after changing token CSS.");
L(md, ">");
L(md, "> Machine-readable copies ship in the package: `_content/CymruBlazor/tokens/tokens.json` and `tokens.d.ts`.");
L(md, "");
L(md, "## Using tokens correctly");
L(md, "");
L(md, "- Always use a name from this page. A misspelt name inside `var(--x, #fallback)` silently renders the");
L(md, "  fallback, which then ignores dark and high-contrast themes.");
L(md, "- Spelling: tokens use **`color`**. Every `--cymru-color-*` token also has a `--cymru-colour-*` alias.");
L(md, "- Prefer **semantic** tokens (`--cymru-color-surface`, `--cymru-color-text`) over primitives");
L(md, "  (`--cymru-blue-800`). Semantic tokens flip with the theme; primitives never do.");
L(md, "- A `Dark` / `High contrast` cell shows where a theme overrides the value. A blank cell means the theme inherits the base value.");
L(md, "");
foreach (var g in allNames.GroupBy(Category).OrderBy(g => g.Key, StringComparer.Ordinal))
{
    L(md, $"## {g.Key}");
    L(md, "");
    L(md, "| Token | Value | Dark | High contrast |");
    L(md, "| --- | --- | --- | --- |");
    foreach (var n in g)
    {
        string Cell(string? v) => v is null ? "" : "`" + v.Replace("|", "\\|") + "`";
        L(md, $"| `{n}` | {Cell(baseDecl.TryGetValue(n, out var b) ? b.Value : null)} | {Cell(dark.GetValueOrDefault(n))} | {Cell(hc.GetValueOrDefault(n))} |");
    }
    L(md, "");
}
outputs[Path.Combine(root, "docs", "design-tokens.md")] = md.ToString();

// ---------- rule: theme scoping ----------
var problems = new List<string>();
var scopedNames = decls.Where(d => ThemeScoped(d.Selector)).Select(d => d.Name).ToHashSet(StringComparer.Ordinal);
// Tokens declared on :root in the *base* token files, with the value they resolve from.
var rootValue = baseDecl.ToDictionary(kv => kv.Key, kv => kv.Value.Value);

foreach (var (themeName, overrides) in new[] { ("dark", dark), ("high-contrast", hc) })
{
    bool DependsOnOverridden(string name, HashSet<string> seen)
    {
        if (!rootValue.TryGetValue(name, out var value) || !seen.Add(name)) return false;
        foreach (Match m in varRef.Matches(value))
        {
            var dep = m.Groups[1].Value;
            if (overrides.ContainsKey(dep)) return true;
            if (DependsOnOverridden(dep, seen)) return true;
        }
        return false;
    }

    foreach (var name in rootValue.Keys.OrderBy(n => n, StringComparer.Ordinal))
    {
        if (overrides.ContainsKey(name)) continue;               // theme sets it explicitly
        if (scopedNames.Contains(name)) continue;                // declared on a theme scope (re-resolves)
        if (DependsOnOverridden(name, new HashSet<string>(StringComparer.Ordinal)))
            problems.Add($"[{themeName}] {name} derives from a token the {themeName} theme overrides, but is declared only on :root, " +
                         "so it keeps the light value inside the theme provider. Declare it in tokens/aliases.css (theme-scoped block) or override it in the theme.");
    }
}

// ---------- write or check ----------
var stale = new List<string>();
foreach (var (path, content) in outputs)
{
    var expected = content.Replace("\r\n", "\n");
    var actual = File.Exists(path) ? File.ReadAllText(path).Replace("\r\n", "\n") : null;
    if (actual == expected) continue;
    if (check) { stale.Add(Path.GetRelativePath(root, path)); continue; }
    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, expected);
    Console.WriteLine($"wrote {Path.GetRelativePath(root, path)}");
}

Console.WriteLine($"{allNames.Count} tokens, {colourNames.Count} colour tokens, {decls.Count} declarations parsed.");

foreach (var p in problems) Console.Error.WriteLine("THEME-SCOPING: " + p);
foreach (var s in stale) Console.Error.WriteLine($"STALE: {s} is out of date - run: dotnet run scripts/GenerateTokens.cs");

if (check && (problems.Count > 0 || stale.Count > 0)) return 1;
if (!check && problems.Count > 0) return 1;
Console.WriteLine(check ? "tokens: up to date, theme-scoping OK" : "tokens: generated, theme-scoping OK");
return 0;

static string FindRoot()
{
    var d = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (d is not null && !File.Exists(Path.Combine(d.FullName, "CymruBlazor.slnx"))) d = d.Parent;
    return d?.FullName ?? throw new InvalidOperationException("Run from inside the repository (CymruBlazor.slnx not found).");
}
